#!/usr/bin/env python3
"""Reproducible orthographic 3D Muse assets. Requires numpy and Pillow.

The model consists of smooth ellipsoids with diffuse/specular lighting. No
runtime 3D engine, downloaded art, or external model is needed on the device.
Run from any directory; generated RGB565 palette/RLE data is checked in.
"""
from pathlib import Path
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "components/muse"
SIZE = 224
POSES = ("neutral", "blink", "listen", "think", "talk", "talk_wide", "happy")


def render(pose):
    n = SIZE * 2
    x, y = np.meshgrid(np.linspace(-1.4, 1.4, n), np.linspace(1.65, -1.55, n))
    rgb = np.zeros((n, n, 3), dtype=float)
    depth = np.full((n, n), -100.)
    light = np.array([-.45, .7, 1.0]); light /= np.linalg.norm(light)

    def ellipsoid(c, r, color, gloss=.1):
        dx, dy = (x - c[0]) / r[0], (y - c[1]) / r[1]
        q = 1 - dx * dx - dy * dy
        z = c[2] + r[2] * np.sqrt(np.maximum(q, 0))
        mask = (q >= 0) & (z > depth)
        normal = np.stack([dx/r[0], dy/r[1], (z-c[2])/(r[2]*r[2])], axis=-1)
        normal /= np.maximum(np.linalg.norm(normal, axis=-1, keepdims=True), .0001)
        diffuse = np.maximum(normal @ light, 0)
        half = light + [0, 0, 1]; half /= np.linalg.norm(half)
        shine = np.maximum(normal @ half, 0) ** 32 * gloss
        color = np.array(color)
        shade = color * (.38 + .62 * diffuse[..., None]) + shine[..., None] * 255
        rgb[mask] = shade[mask]; depth[mask] = z[mask]

    cream = (250, 241, 225)
    # Feet, relaxed arms, softly tapered torso and oversized rounded hood.
    ellipsoid((-.30, -1.05, .05), (.28, .17, .32), (211, 196, 174))
    ellipsoid((.30, -1.05, .05), (.28, .17, .32), (231, 218, 197))
    arm_y = -.31 if pose != "happy" else .05
    ellipsoid((-.64, arm_y, .02), (.21, .39, .24), cream)
    ellipsoid((.64, arm_y, .02), (.21, .39, .24), cream)
    ellipsoid((0, -.49, .06), (.60, .63, .46), cream)
    ellipsoid((0, .54, .01), (.93, .87, .64), cream, .16)
    # Face bezel and a subtly recessed, warm porcelain face.
    ellipsoid((0, .54, .527), (.70, .60, .16), (208, 191, 169))
    ellipsoid((0, .56, .605), (.64, .54, .115), (255, 250, 239), .06)
    look = .045 if pose == "think" else -.02 if pose == "listen" else 0
    for ex in (-.23, .23):
        ey, eh = .65, .102
        if pose == "blink": ey, eh = .61, .019
        if pose == "happy": ey, eh = .68, .035
        ellipsoid((ex+look, ey, .718), (.063, eh, .034), (24, 24, 24), .18)
        if eh > .05:
            ellipsoid((ex+look-.013, ey+.027, .748), (.017, .022, .01), (255, 252, 240), .1)
    mouth = .018 if pose not in ("talk", "talk_wide", "happy") else .054 if pose == "talk" else .085
    ellipsoid((look, .34, .706), (.075, mouth, .027), (69, 49, 39), .02)
    if mouth > .05:
        ellipsoid((look, .31, .729), (.044, .019, .007), (234, 130, 98))
    # Small orange enamel pin, the only saturated detail.
    ellipsoid((.18, -.53, .508), (.095, .095, .037), (255, 60, 0), .22)
    return Image.fromarray(np.uint8(np.clip(rgb, 0, 255))).resize((SIZE, SIZE), Image.Resampling.LANCZOS)


def rle(values):
    result = bytearray(); values = list(values); i = 0
    while i < len(values):
        count = 1
        while i + count < len(values) and values[i+count] == values[i] and count < 255:
            count += 1
        result.extend((count, values[i])); i += count
    return result


def main():
    images = [render(p) for p in POSES]
    atlas = Image.new("RGB", (SIZE * len(images), SIZE))
    for i, im in enumerate(images): atlas.paste(im, (i * SIZE, 0))
    palette = atlas.quantize(colors=256, method=Image.Quantize.MEDIANCUT)
    colors = palette.getpalette()
    rgb565 = [(colors[i] >> 3) << 11 | (colors[i+1] >> 2) << 5 | colors[i+2] >> 3 for i in range(0, 768, 3)]
    data = bytearray(); offsets = []
    for size in (SIZE, 96):
        for im in images:
            offsets.append(len(data))
            indexed = im.resize((size, size), Image.Resampling.LANCZOS).quantize(palette=palette, dither=Image.Dither.FLOYDSTEINBERG)
            data += rle(indexed.tobytes())
    offsets.append(len(data))
    def numbers(seq, width, fmt):
        return "\n".join("    " + ",".join(fmt(v) for v in seq[i:i+width]) + "," for i in range(0, len(seq), width))
    source = "/* Generated by tools/muse/render_character.py. Original Muse ellipsoid model. */\n#include <stdint.h>\n"
    source += "const uint16_t muse_character_palette[256] = {\n" + numbers(rgb565, 12, lambda v: f"0x{v:04x}") + "\n};\n"
    source += "const uint32_t muse_character_offsets[15] = {" + ",".join(map(str, offsets)) + "};\n"
    source += "const uint8_t muse_character_rle[] = {\n" + numbers(data, 32, str) + "\n};\n"
    (OUT / "muse_character_data.c").write_text(source)
    preview = ROOT / "simulator/screenshots/refined-character.png"
    preview.parent.mkdir(parents=True, exist_ok=True); atlas.save(preview)
    print(f"Character: {len(data) + 512 + 60:,} flash bytes; preview {preview}")


if __name__ == "__main__": main()
